### ISSUE TITLE
Fix issues raised by golint

### ISSUE THREAD

**Issue by distortedsignal** [bluek8s/kubedirector#103]
Currently, the number of linting errors raised by `golint` (doing `golint ./...` in the root directory) is over 9000.

<img width="462" alt="screen shot 2018-10-31 at 3 28 06 pm" src="https://user-images.githubusercontent.com/2186874/47822513-a06da680-dd21-11e8-946c-da9596142fc1.png">

I would like to bring this number down to something that is lower. I don't have a particular target in mind, but I think that "lower" is a good enough target for now.

**Comment by joel-bluedata** [comment]
We can't do much about the package dependencies. If you limit golint's output to just the code in the kubedirector repo, there are 46 issues. They seem almost entirely about opinions w.r.t. proper camelcasing. :-) I agree it would be nice to get that output clean. All yours, if you want it.

**Comment by distortedsignal** [comment]
I don't appreciate your pessimism RE our dependencies - we CAN make pull requests to ALL THE REPOS. /s

I'll get to it... when I get to it. Not sure when that's going to be.

**Comment by joel-bluedata** [comment]
:-)

**Comment by distortedsignal** [comment]
I'll probably end up using a simple pipeline as a check - this seems to do the trick:

`golint $(ls -d */ | grep -v "vendor/" | sed -e "s/^\(.*\)$/\1.../g") | wc -l`

Currently it looks like this:
<img width="639" alt="screen shot 2018-10-31 at 4 48 34 pm" src="https://user-images.githubusercontent.com/2186874/47825002-e3814700-dd2c-11e8-8cd6-f94111d40573.png">

**Comment by joel-bluedata** [comment]
Should be able to clean this up quite a bit using just gorename to address the camelcasing gripes.

But let's do it for 0.3 since 0.2 is in the settling-down phase.
