### ISSUE TITLE
more top-level cluster status

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#11]
Should have a top-level status message (beyond just the state) and possibly an event history. For example, we need some place to advertise a failure in running lifecycle event notifications, or a failure to reconcile K8s objects.

**Comment by swamibluedata** [comment]
@joel can we create a cluster level events array that logs all the events. We can implement just for errors for now

**Comment by joel-bluedata** [comment]
Absolutely. I'd like for us to take a quick look at whether we can just make use of normal K8s events, maybe through EventRecorder in client-go.
