### ISSUE TITLE
investigate CI solutions

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#16]

**Comment by distortedsignal** [comment]
I'm going with Travis CI for now, because it seems like that's an ok place to start. If we want to move to CircleCI later (or another third party - I'm not picky, just so long as it's accessible), I'll open a new issue to migrate over to that third party.

**Comment by distortedsignal** [comment]
I feel like this could be moved to "done" - we're set up on TravisCI, and we have the option to make pre-push hooks. What more do we need here?
