### ISSUE TITLE
"clusters using app" needs fixing for new namespace behavior

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#164]
In admitAppCR when an app resource is being modified or deleted, we call reconciler.ClustersUsingApp to see if the operation is safe. Currently this just sees whether any cluster is referencing an app resource with that name.

As of PR #160 though it is entirely possible for an app to have that name but not be in use by any cluster (because of the namespace it is in). So this check needs to be namespace-aware.

**Comment by swamibluedata** [comment]
- Add a field in cluster CRD "AppNamespace". This will be an optional filed.
   -- If left empty, mutating webhook will automatically populate that to the namespace where the app is picked up from.
   -- If <app_namespace> is included, it can be either be current namespace or kubedirector's namespace (for now). In the future we can allow other namespaces if required.
- clusterKey will also include app namespace
- ClustersUsingApp will use the app namespace for verification.

**Comment by joel-bluedata** [comment]
I think the approach of having the app namespace specified in the KDC spec is asking a bit too much of the user/client that is submitting it. It also might allow for subverting the intent of an admin that has provided a namespace-specific KDA.

Let's talk a bit in person when you're free.

**Comment by swamibluedata** [comment]
Made some changes for this. We do need to store app_namespace in the cluster cr somewhere, instead of making the user specify it through the cluster spec, our mutation webhook will store the app namespace name in the "status" object instead
