### ISSUE TITLE
discover if/how metrics service object is cleaned up

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#174]
In cmd/manager/main.go on the new operator SDK branch, a metrics service is created. How is it (or how is it intended to be) cleaned up when KubeDirector is undeployed?

**Comment by don-milos** [comment]
Deleting the kubedirector deployments is deleting the metrics service.

# kubectl delete -f deploy/kubedirector/deployment-localbuilt.yaml –now
Here’s the deployment and service objects.

# kc describe deployment kubedirector
Name:                   kubedirector
Namespace:              default
CreationTimestamp:      Mon, 29 Jul 2019 11:41:28 -0400
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               name=kubedirector
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           name=kubedirector
  Service Account:  kubedirector
  Containers:
   kubedirector:
    Image:      donmilos1/kubedirector:unstable
    Port:       60000/TCP
    Host Port:  0/TCP
    Command:
      /bin/sh
    Args:
      -c
      mkfifo /tmp/fifo; (/usr/local/bin/kubedirector &> /tmp/fifo) & while true; do cat /tmp/fifo; done
    Environment:
      MY_NAMESPACE:      (v1:metadata.namespace)
      WATCH_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    kubedirector
    Mounts:             <none>
  Volumes:              <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubedirector-7f97d5959b (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  109s  deployment-controller  Scaled up replica set kubedirector-7f97d5959b to 1

# kc get service
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
kubedirector             ClusterIP   10.105.227.146   <none>        60000/TCP   2m54s
# kc describe service kubedirector
Name:              kubedirector
Namespace:         default
Labels:            name=kubedirector
Annotations:       <none>
Selector:          name=kubedirector
Type:              ClusterIP
IP:                10.101.67.76
Port:              metrics  60000/TCP
TargetPort:        60000/TCP
Endpoints:         192.168.0.95:60000
Session Affinity:  None
Events:            <none>

**Comment by joel-bluedata** [comment]
I'm puzzled as to why deleting the deployment would also automatically delete that service. Probably something obvious I'm missing. Will come back to this later.

**Comment by don-milos** [comment]
The following code in the operator-framework/metrics/metrics.go/initOperatorService() sets an owner reference on the service so that when the pod is deleted the service is too:

	ownRef, err := getPodOwnerRef(ctx, client, namespace)
	if err != nil {
		return nil, err
	}
	service.SetOwnerReferences([]metav1.OwnerReference{*ownRef})

**Comment by joel-bluedata** [comment]
Ah ha! Good enough for me.
