### ISSUE TITLE
why is the storage.size KDC property always required?

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#175]
Observed by Don in his development setup.

On the master branch, it's not required unless the storage object is present.

First thing is to get clear about what the failure mode is, then investigate the difference between that branch and the main branch (or between Don's setup and others).

**Comment by don-milos** [comment]
I believe the new operator-sdk schema validator was getting confused because Role.Storage is an optional property but it was a struct and not a pointer. The same goes for ClusterStorage.Size. I made Role.Storage a pointer and it resolved the issue.

I created a pull request with the fix.
