### ISSUE TITLE
investigate namespace watch behavior with new operator SDK

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#177]
Desired behavior:
* KD watches ALL namespaces for KDC objects.
* KD watches only ITS OWN namespace for KD Config object.

Is this the case on the new operator SDK branch?

And, what is the namespace passed to the manager object used for?

**Comment by don-milos** [comment]
It looks like this is a known issue that will possibly be solved with the next stable release of controller-runtime v0.2.0.

https://github.com/operator-framework/operator-sdk/issues/767
https://github.com/elastic/cloud-on-k8s/issues/405

For the time being it looks like we're stuck with watching all namespaces or just one. The current code watches only the default namespace. That's the namespace that is currently passed to the manager object.

I can modify the code to watch all namespaces for both resources by passing Namespace:"" to the manager if you like?

**Comment by joel-bluedata** [comment]
A quick glance at that change for the 0.2.0 controller-runtime still seems to indicate that the set of watchable namespaces is the same for all watched resources. If so that still doesn't map to what we are expecting to do here.

The solution might be to watch all namespaces, but specifically for KDConfig we only pay attention to the object if it is in our own namespace.

We could reject bad-namespace KDConfig objects in the validator, or ignore them in the controller.

**Comment by don-milos** [comment]
I like the idea of rejecting KDConfig objects in the validator when the namespace is bad. I will start implementing that.
