### ISSUE TITLE
"make redeploy" broken with ubi-minimal base image

### ISSUE THREAD

**Issue by don-milos** [bluek8s/kubedirector#184]
make redeploy is broken on the operator-sdk-v0.8.1 branch because of the move to the RedHat ubi-minimal base image. The killall command isn't installed by default.

**Comment by don-milos** [comment]
I tried adding the following to the Dockerfile:

RUN  microdnf -y install --nodocs python-rhsm-certificates \
    && microdnf -y install --nodocs psmisc procps-ng \
    && microdnf clean all

Make redeploy worked after that but I had to install python-rhsm-certificates (Joel's workaround for the RedHat  subscription issue) to get the ps and killall packages installed. Is that ok?

**Comment by joel-bluedata** [comment]
Maybe we can use something other than killall? Will investigate.

**Comment by joel-bluedata** [comment]
@swamibluedata might have thoughts too, who knows!

**Comment by joel-bluedata** [comment]
Interestingly I can add those to the Dockerfile WITHOUT the install of python-rhsm-certificates and it build ok (on my Mac).

Do you still have python-rhsm-certificates installed on your base host? I'm wondering how/why the base host would matter in this case. I skimmed https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#adding_software_inside_the_minimal_ubi_container but I am not sure that really clears things up.

Some further reading reveals that Docker on RHEL automatically mounts a base host directory into /run/secrets and maybe the Docker you have on CentOS does the same. Perhaps the _absence_ of that directory on macOS Docker is what lets me build without shenanigans.

i'm going to experiment a bit more. You could try doing the following with your image:
```
docker run -d --name=test registry.access.redhat.com/ubi7/ubi-minimal:latest /bin/bash -c "while true; do sleep 100; done"
docker exec -it <container ID goes here> /bin/bash
inside container, install those additional packages
inside the container, run the "mount" command to see if /run/secrets is mounted
```

I don't think it's necessarily bad to install python-rhsm-certificates BTW but it feels weird. If we do end up needing it to install stuff then maybe we should strip it out again when we're done. But perhaps there is a better solution for CentOS build environments. E.g. perhaps: https://patrick.uiterwijk.org/blog/2016/10/6/rhel-containers-on-non-rhel-hosts

...but that (even if it works) requires modifying the compilation environment a further amount which is kind of icky.

**Comment by joel-bluedata** [comment]
Interestingly, on a CentOS host I can't run microdnf at all inside a running container... "inappropriate ioctl for device". So I made a similar Dockerfile to get those packages installed and launched a container from that.

And yeah, inside the container I see:
```shell
bash-4.2# mount | grep secrets
/dev/mapper/VolBDSCStore-thinpool on /run/secrets type xfs (rw,relatime,seclabel,attr2,inode64,logbsize=64k,sunit=128,swidth=256,prjquota)
```
seems to be the same content as /usr/share/rhel/secrets/rhsm/ca/redhat-uep.pem on the base host.

OK so what does this mean?

It may be that following the tips in https://patrick.uiterwijk.org/blog/2016/10/6/rhel-containers-on-non-rhel-hosts would obviate any need to use python-rhsm-certificates when pulling down the ubi-minimal image AND when building the Dockerfile that uses microdnf. I.e. maybe we wouldn't need to install python-rhsm-certificates either in the base host or in the Dockerfile. Haven't tried that yet.

**Comment by don-milos** [comment]
Are you sure your successful operations are not due to previously cached images?

I started with a clean environment and here are my steps and results in order:

- I'm running on CentOS 7.
- I started with the subscription-manager-rhsm-certificates package installed and python-rhsm-certificates NOT installed. 
- I tried (kubedirector) make build and got the following error:
        Step 1/6 : FROM registry.access.redhat.com/ubi7/ubi-minimal:latest
        Trying to pull repository registry.access.redhat.com/ubi7/ubi-minimal ...
        open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
- I uninstalled the subscription-manager-rhsm-certificates package and got the same make build failure.
- I installed the python-rhsm-certificates package and the make build succeeded.
- I deployed kubedirector and connected to the its pod.
- The ps and killall commands were not present.
- I tried “microdnf -y install --nodocs psmisc procps-ng” and the command failed with the message, “error: gpgme_op_import() error: Inappropriate ioctl for device”.
- I tried “microdnf -y install --nodocs python-rhsm-certificates” and that command failed with the same error message. Interestingly, when I run these commands while building the image , they succeed.
- My other observation is that /run/secrets is always mounted but empty except for the secret that KubeDirector creates.

Are we sure that we want to move to the ubi-minimum image?

We could possibly workaround the missing killall command by using the contents of /proc items but the fact that there are so many missing utilities (e.g. ps, killall, mount, umount, which, etc.) makes the debugging of these images more difficult. I also tried for the better part of an afternoon to get the dlv debugger working again on the ubi-minimum image and couldn’t. The Alpine image was much easier to use.

**Comment by don-milos** [comment]
I made some progress. I still had to install the python-rhsm-certificates package on the host where I build the KubeDirector image in order to get pull down the ubi-minimal image.

I used the ubi8/ubi-minimal:latest image instead of the ubi7 version of the image and added the following commands to the Dockerfile as documented on this page https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index?extIdCarryOver=true&sc_cid=701f2000001OH7JAAW#build_a_ubi_based_image:

        RUN microdnf update -y && rm -rf /var/cache/yum

        RUN microdnf -y install --nodocs psmisc procps-ng \
            && microdnf clean all

The resulting image had ps and killall properly installed.

**Comment by joel-bluedata** [comment]
That looks great. What a hassle to figure this out! But I think if that's the end solution then yeah we should stick with ubi-minimal.

Did ubi7 not work? ... what was the failure mode for that? ubi8 is probably fine, just curious.

**Comment by don-milos** [comment]
I retried ubi7 with the new Dockerfile changes and it works. I will create a push request.
