### ISSUE TITLE
Newbie: build kubedirector error Couldn't resolve host name for https://cdn-ubi.redhat.com/...

### ISSUE THREAD

**Issue by migmurillo** [bluek8s/kubedirector#239]
Hello,

I have an error probably trivial but I don't know how to fix to build kubedirector.

I have added on /etc/resolv.conf all DNS to solve the dns entries but still fail the build.

1. ERROR: make
[root@rhel01 kubedirector]# make

* Creating KubeDirector deployment image and YAML...
operator-sdk build bluek8s/kubedirector:0.3.0
INFO[0058] Building OCI image bluek8s/kubedirector:0.3.0
Sending build context to Docker daemon  313.1MB
Step 1/13 : FROM registry.access.redhat.com/ubi7/ubi-minimal:latest
 ---> 2b4f0d37c483
Step 2/13 : ENV USER_UID=1001     USER_NAME=kubedirector     USER_HOME=/home/kubedirector     OPERATOR=/home/kubedirector/kubedirector     OPERATOR_BUILD_SRC=build/_output/bin/kubedirector
 ---> Using cache
 ---> 1a1b0d0365ae
Step 3/13 : RUN microdnf update -y && rm -rf /var/cache/yum
 ---> Using cache
 ---> 72cf72d45ec0
Step 4/13 : RUN microdnf -y install --nodocs psmisc procps-ng     && microdnf clean all
 ---> Running in 0f2e68023aa8

(microdnf:6): librhsm-WARNING **: 22:04:31.270: Found 0 entitlement certificates

(microdnf:6): librhsm-WARNING **: 22:04:31.271: Found 0 entitlement certificates
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:04:38.774: Skipping refresh of ubi-7: cannot update repo 'ubi-7': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:04:49.730: Skipping refresh of ubi-7-server-optional-rpms: cannot update repo 'ubi-7-server-optional-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/optional/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:04:58.677: Skipping refresh of ubi-7-server-extras-rpms: cannot update repo 'ubi-7-server-extras-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/extras/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:05:07.649: Skipping refresh of ubi-7-rhah: cannot update repo 'ubi-7-rhah': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/atomic/7/7Server/x86_64/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:05:16.509: Skipping refresh of ubi-server-rhscl-7-rpms: cannot update repo 'ubi-server-rhscl-7-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/rhscl/1/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 22:05:25.394: Skipping refresh of ubi-7-server-devtools-rpms: cannot update repo 'ubi-7-server-devtools-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/devtools/1/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com; Unknown error]
error: No package matches 'psmisc'
The command '/bin/sh -c microdnf -y install --nodocs psmisc procps-ng     && microdnf clean all' returned a non-zero code: 1
Error: failed to output build image bluek8s/kubedirector:0.3.0: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "bluek8s/kubedirector:0.3.0", "."}: exit status 1)
Usage:
  operator-sdk build <image> [flags]

Flags:
  -h, --help                      help for build
      --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --image-builder string      Tool to build OCI images. One of: [docker, buildah] (default "docker")

Global Flags:
      --verbose   Enable verbose logging

make: *** [Makefile:52: build] Error 1
 

2. VERIFICATION ACCESS:
[root@rhel01 kubedirector]#    wget https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/devtools/1/os/repodata/repomd.xml
--2020-01-02 01:45:55--  https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/devtools/1/os/repodata/repomd.xml
Resolving cdn-ubi.redhat.com (cdn-ubi.redhat.com)... 184.50.167.214
Connecting to cdn-ubi.redhat.com (cdn-ubi.redhat.com)|184.50.167.214|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3850 (3.8K) [application/xml]
Saving to: ‘repomd.xml.1’

repomd.xml.1                              100%[==================================================================================>]   3.76K  --.-KB/s    in 0s

2020-01-02 01:45:56 (164 MB/s) - ‘repomd.xml.1’ saved [3850/3850]

[root@rhel01 kubedirector]# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 9.9.9.9
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4

Thanks in advance,
Miguel

**Comment by migmurillo** [comment]
Using version 0.3.0, redhat 8.1

**Comment by swamibluedata** [comment]
Looks like docker daemon is not setup properly to have access to internet or resolve hostnames. So the container is not able to access internet or resolve dns info? After modifying the /etc/resolv.conf, have you tried restarting docker demon? You can also change daemon.json to include the dns servers.

**Comment by migmurillo** [comment]
Thanks swami,

I have fixed the issue finally adding proxy env on Dockerfile.
 
ENV http_proxy=web-proxy:8088
ENV https_proxy=web-proxy:8088

Best Regards
Miguel

**Comment by migmurillo** [comment]
I forgot to comment that my server is behind a VPN with proxy, it is because I needed to add it.
Thanks for your support.
Best regards
Miguel

**Comment by joel-bluedata** [comment]
Glad you got it working!
