### ISSUE TITLE
Consider adding additionalPrinterColumns to CRD

### ISSUE THREAD

**Issue by swamibluedata** [bluek8s/kubedirector#288]
To all our CRDs, we could define any columns that will be shown to the user through kubectl get

For (e.g) if we add .spec.app as one such field, kuebctl get kubedirectorclusters will show the app name as well. 

Refer to this page.
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/

**Comment by joel-bluedata** [comment]
We do have shortnames.

**Comment by joel-bluedata** [comment]
Leaving this in 0.10.0 for now since we're generally messing with the CRDs in 0.10.0 ... might be good to do this at the same time.
