### ISSUE TITLE
get wrong fqdn in pod

### ISSUE THREAD

**Issue by Pandoraemon** [bluek8s/kubedirector#291]
2020-04-08 12:38:20,869 INFO bluedata_edit_cluster Currently registered hosts with CM [u'10-42-4-61.s-kdss-dcgmm-9.cdh.svc.cluster.local', u'kdss-dcgmm-0.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-1.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-10.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-11.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-12.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-13.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-3.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-4.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-5.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-7.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-dcgmm-8.kdhs-wmtmt.cdh.svc.cluster.local', u'kdss-qf8dg-0.kdhs-wmtmt.cdh.svc.cluster.local']

some worker pod get wrong fqdn like 10-42-4-61.s-kdss-dcgmm-9.cdh.svc.cluster.local which should be kdss-dcgmm-9.kdhs-wmtmt.cdh.svc.cluster.loca

**Comment by joel-bluedata** [comment]
Do you know if the K8s cluster is using CoreDNS or Kube-DNS? Or... if this is a K8s cluster created by some cloud service, which service are you using?

----------

@swamibluedata I'm thinking this could be the CoreDNS issue that they fixed in https://github.com/coredns/coredns/pull/3687 . I also thought we had an issue around here that was tracking that, but I don't see one.

(If it _is_ that issue, it should be fixed in CoreDNS 1.6.8 or later.)

**Comment by riteshja** [comment]
@joel-bluedata @swamibluedata 
So, what we have observed in HPECP K8s clusters during the development of CDH 6.x app is this 
- nslookup of the pod IP address in the cmserver pod returns the hostname with IP prepended(even after updating the coredns deployment to use the latest bluedata docker image).
- nslookup of the pod IP address in a centos7x KD app returns the correct hostname without the IP prepended.

That led us to think that, may be, the base centos 7x image used by the CDH app is not correct. So we updated the base image to be the one used in the centos 7x KD app. We are still seeing the same issue.

We worked around this issue by making `nsswitch.conf` in the container to read from /etc/hosts first.
`hosts: dns  files yhostname` -> `hosts: files dns yhostname`

**Comment by joel-bluedata** [comment]
Yes, I'm almost certain that's the CoreDNS issue, tho Swami can confirm. I don't think it's purely solvable unless/until we can deploy CoreDNS 1.6.8 or later.

**Comment by swamibluedata** [comment]
Yes it is the coredns issue. 
Also nsswitch.conf change will work for kubedirector clusters, since we configure /etc/resolv.conf correctly

**Comment by swamibluedata** [comment]
You can test it out by using 

bluedata/coredns:latest 

image tag for coredns deployment

**Comment by Pandoraemon** [comment]
Yes, We use  rancher/coredns-coredns:1.6.5

**Comment by joel-bluedata** [comment]
Can you validate whether this works correctly with CoreDNS 1.6.8? If so, I'll close this issue.

**Comment by Pandoraemon** [comment]
solved with edit nsswitch.conf config file. cloes
