### ISSUE TITLE
add woker node to cdh can not work

### ISSUE THREAD

**Issue by Pandoraemon** [bluek8s/kubedirector#308]
{"level":"info","ts":1589017791.0068526,"logger":"controller_kubedirectorcluster","msg":"waiting for replicas count for role{worker}: 2 -> 4","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017791.0146863,"logger":"controller_kubedirectorcluster","msg":"waiting for replicas count for role{worker}: 2 -> 4","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.0559814,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.0559926,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.277333,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.6776502,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017853.518963,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017853.9157438,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017855.542778,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017855.9417949,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017857.6660178,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017858.0749185,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017859.6916547,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017860.0988066,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017861.7157881,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.126658,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.1326196,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.132619,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.241284,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-k227s-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.33518,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.3405993,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.4455178,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.4511223,"logger":"controller_kubedirectorcluster","msg":"stable","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}

I add 2 more worker nodes to the cdh cluster, but looks it  not  notify new members about member changes to master and old worker nodes in 0.4.1 which work well with 0.4.0

**Comment by joel-bluedata** [comment]
Can I double check, are you running the 0.4.1 tagged image or is this a build from tip of master?

**Comment by Pandoraemon** [comment]
I pulled this image bluek8s/kubedirector:0.4.1

**Comment by joel-bluedata** [comment]
Got it, thanks. I'll see if I can reproduce. If you happen to have the whole KD log (rather than just the snippet above), that could be useful.

**Comment by neogeographica** [comment]
OK, I've reproduced. Will work on it today.

**Comment by joel-bluedata** [comment]
OK, I've reproduced. Will work on it today.

**Comment by joel-bluedata** [comment]
Should be fixed on master. I'll leave this issue open until I cut the 0.4.2 release with the relevant part for this fix backported.
