### ISSUE TITLE
can not add nodes with cdh6 

### ISSUE THREAD

**Issue by Pandoraemon** [bluek8s/kubedirector#318]
looks run cluster_setup.py when I add more workers into cluster

[root@kdss-b9ngg-0 guestconfig]# cat configpackage-20200526095508.log
EXECUTING: chmod -R 777 /data
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/nsswitch.conf /etc/nsswitch.conf
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/limits.conf /etc/security/limits.conf
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/logind.conf /etc/systemd/logind.conf
EXECUTING: mkdir -p /usr/share/java/
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/mysql-connector-java.jar /usr/share/java/mysql-connector-java.jar
Starting setup for kdss-b9ngg-0.kdhs-vcj2z.cdh.svc.cluster.local, role: cmserver
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/hive-schema-2.1.1.mysql.sql /opt/hive-tables-sql/hive-schema-2.1.1.mysql.sql
EXECUTING: sed -i s/CDH_PARCEL_VERSION/CDH-6.3.2-1.cdh6.3.2.p0.1605554/g /opt/hive-tables-sql/hive-schema-2.1.1.mysql.sql
EXECUTING: cp -f /opt/guestconfig/cdh6-cm-setup/my.cnf /etc/my.cnf
EXECUTING: rm -f /var/lib/mysql/ib_logfile0 /var/lib/mysql/ib_logfile1
Started mysql on kdss-b9ngg-0.kdhs-vcj2z.cdh.svc.cluster.local
EXECUTING: /opt/cloudera/cm/schema/scm_prepare_database.sh -u root mysql amon amon amon_password as sudo
JAVA_HOME=/usr/java/jdk
Verifying that we can write to /etc/cloudera-scm-server
Database type: mysql
Database user: root
Executing: /usr/java/jdk/bin/java -cp /usr/share/java/mysql-connector-java.jar:/usr/share/java/oracle-connector-java.jar:/usr/share/java/postgresql-connector-java.jar:/opt/cloudera/cm/schema/../lib/* com.cloudera.enterprise.dbutil.DbProvisioner --create -h localhost -u root -H localhost -U amon -d amon -t mysql
[                          main] DbProvisioner                  ERROR Exception when creating/dropping database with user 'root' and jdbc url 'jdbc:mysql://localhost/?useUnicode=true&characterEncoding=UTF-8'
java.sql.SQLException: Can't create database 'amon'; database exists
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)[mysql-connector-java.jar:5.1.41]
	at com.cloudera.enterprise.dbutil.DbProvisioner.executeSql(DbProvisioner.java:299)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
	at com.cloudera.enterprise.dbutil.DbProvisioner.doMain(DbProvisioner.java:104)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
	at com.cloudera.enterprise.dbutil.DbProvisioner.main(DbProvisioner.java:123)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
[                          main] DbProvisioner                  ERROR Stack Trace:
java.sql.SQLException: Can't create database 'amon'; database exists
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)[mysql-connector-java.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)[mysql-connector-java.jar:5.1.41]
	at com.cloudera.enterprise.dbutil.DbProvisioner.executeSql(DbProvisioner.java:299)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
	at com.cloudera.enterprise.dbutil.DbProvisioner.doMain(DbProvisioner.java:104)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
	at com.cloudera.enterprise.dbutil.DbProvisioner.main(DbProvisioner.java:123)[db-common-6.3.1.96818eaab0a222aa84a7854b8d22c0c7.jar:]
--> Error 1, giving up (use --force if you wish to ignore the error)
Failed to exec: /opt/cloudera/cm/schema/scm_prepare_database.sh -u root mysql amon amon amon_password
{"level":"info","ts":1590486650.371913,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-hklqr-0}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486652.4019835,"logger":"controller_kubedirectorcluster","msg":"changing replicas count for role{worker}: 3 -> 5","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486652.4161825,"logger":"controller_kubedirectorcluster","msg":"waiting for replicas count for role{worker}: 3 -> 5","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486686.3556755,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486686.3557172,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486686.4580038,"logger":"controller_kubedirectorcluster","msg":"running systemd check in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486686.4669034,"logger":"controller_kubedirectorcluster","msg":"running systemd check in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486688.591748,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486688.6155574,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486690.8470678,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486690.8609767,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486692.8784738,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486692.8858886,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486695.0119536,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486695.0190766,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486697.039253,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486697.0454762,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.0661342,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-hklqr-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.0747504,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-hklqr-4} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.0820808,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-hklqr-4}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.082106,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-hklqr-3}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.1864161,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-hklqr-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.188933,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-hklqr-4} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.1891131,"logger":"controller_kubedirectorcluster","msg":"will notify member{kdss-b9ngg-0}: addnodes","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"info","ts":1590486699.189169,"logger":"controller_kubedirectorcluster","msg":"running app reconfig in pod{kdss-b9ngg-0}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"error","ts":1590486701.2144122,"logger":"controller_kubedirectorcluster","msg":"failed to notify member{kdss-b9ngg-0} about member changes","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent","error":"command terminated with exit code 120","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/pandoraemon/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/bluek8s/kubedirector/pkg/shared.LogErrorf\n\tkubedirector/pkg/shared/logging.go:100\ngithub.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.syncMemberNotifies.func1\n\tkubedirector/pkg/controller/kubedirectorcluster/members.go:206"}
{"level":"info","ts":1590486701.2221477,"logger":"controller_kubedirectorcluster","msg":"running app reconfig in pod{kdss-b9ngg-0}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"error","ts":1590486703.248738,"logger":"controller_kubedirectorcluster","msg":"failed to notify member{kdss-b9ngg-0} about member changes","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent","error":"command terminated with exit code 120","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/pandoraemon/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/bluek8s/kubedirector/pkg/shared.LogErrorf\n\tkubedirector/pkg/shared/logging.go:100\ngithub.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.syncMemberNotifies.func1\n\tkubedirector/pkg/controller/kubedirectorcluster/members.go:206"}
{"level":"info","ts":1590486703.2564592,"logger":"controller_kubedirectorcluster","msg":"running app reconfig in pod{kdss-b9ngg-0}","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent"}
{"level":"error","ts":1590486705.2817936,"logger":"controller_kubedirectorcluster","msg":"failed to notify member{kdss-b9ngg-0} about member changes","Request.Namespace":"cdh","Request.Name":"cdh632-cm-persistent","error":"command terminated with exit code 120","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/pandoraemon/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/bluek8s/kubedirector/pkg/shared.LogErrorf\n\tkubedirector/pkg/shared/logging.go:100\ngithub.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.syncMemberNotifies.func1\n\tkubedirector/pkg/controller/kubedirectorcluster/members.go:206"}

**Comment by omhpe** [comment]
Hi @Pandoraemon ,
We are working on this and the fix should be available soon.
