### ISSUE TITLE
 docker.io/bluedata/cdh632multi:1.1 image is too large

### ISSUE THREAD

**Issue by Pandoraemon** [bluek8s/kubedirector#333]
The  image is too large, where I can found the Dockerfile of this image and I want to make it smaller.

**Comment by joel-bluedata** [comment]
PR #325 is about to update that image... are you using the new kdapp+image from that PR, or the current one in master?

In either case @omhpe would be the contact point since they are providing these images. I'm sure the Dockerfile can be shared.

**Comment by omhpe** [comment]
@Pandoraemon Please find attached docker file. It is a zip, you can extract the file
[Dockerfile.zip](https://github.com/bluek8s/kubedirector/files/4774217/Dockerfile.zip)
