### ISSUE TITLE
possible to specify kdcluster name that prevents member pod creation

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#387]
The kdcluster name is incorporated into the volume names for cgroup and cgroup-systemd, for kdclusters from systemd-using apps (cf. generateSystemdSupport). This can break things because some characters e.g. "." are valid in CR names but not in volume names. The symptom is that the statefulset will refuse to ever create the pods.

I don't immediately know of a reason why we need to incorporate the CR names into those volume names, so this might be a quick fix.

**Comment by swamibluedata** [comment]
So it this a mapr related issue? Or pvcs cannot have "."

**Comment by joel-bluedata** [comment]
Not MapR related. Just the set of allowed characters for volume names in container specs.

**Comment by swamibluedata** [comment]
So PVCs can have "." right?

[jenkins@swami-vm07 ~]$ kubectl get pvc
NAME       STATUS   VOLUME                                         CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test.pvc   Bound    mapr-pv-d256b7e2-dad5-49c1-8590-886ab0dca0d8   1Gi        RWO            default        24s

**Comment by joel-bluedata** [comment]
Looks like it!
