### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Ivaylo68Ma** [bluek8s/kubedirector#408]
I've started mak deploy but the followin errors occured:

ivo@kube-master:~/kubedirector$ make deploy

* Creating custom resource definitions...
kubectl create -f deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/kubedirectorapps.kubedirector.hpe.com created
kubectl create -f deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/kubedirectorclusters.kubedirector.hpe.com created
kubectl create -f deploy/kubedirector/kubedirector.hpe.com_kubedirectorconfigs_crd.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/kubedirectorconfigs.kubedirector.hpe.com created

* Creating role and service account...
kubectl create -f deploy/kubedirector/rbac.yaml
clusterrole.rbac.authorization.k8s.io/kubedirector created
serviceaccount/kubedirector created
clusterrolebinding.rbac.authorization.k8s.io/kubedirector created

* Deploying PRE-BUILT KubeDirector...
kubectl create -f deploy/kubedirector/deployment-prebuilt.yaml
deployment.apps/kubedirector created

* Waiting for KubeDirector to start............

* Creating example application types...
kubectl create -f deploy/example_catalog/
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-cassandra-3.11.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector                     .hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-cdh5142cm.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.                     com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-cdh632cm.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.c                     om": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-centos7.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.co                     m": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": dial tcp 10.98.173.35:443: i/o timeout
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-centos8.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.co                     m": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-deployment-engine.json": Internal error occurred: failed calling webhook "validate-cr.kubedirec                     tor.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-elk771.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.com                     ": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-gitlab-ee.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.                     com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": dial tcp 10.98.173.35:443: i/o timeout
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-jupyter-notebook.json": Internal error occurred: failed calling webhook "validate-cr.kubedirect                     or.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-kafka55.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.co                     m": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-mapr610-secured.json": Internal error occurred: failed calling webhook "validate-cr.kubedirecto                     r.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-spark221e2.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe                     .com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-spark245.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hpe.c                     om": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-tensorflow-cpu-dockerhub.json": Internal error occurred: failed calling webhook "validate-cr.ku                     bedirector.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-tensorflow-gpu-dockerhub.json": Internal error occurred: failed calling webhook "validate-cr.ku                     bedirector.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": dial tcp 10.98.173.35:443: i/o timeout
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-training-engine.json": Internal error occurred: failed calling webhook "validate-cr.kubedirecto                     r.hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-ubuntu18.04.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector.hp                     e.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
make: *** [Makefile:101: deploy] Error 1
ivo@kube-master:~/kubedirector$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
kubedirector-75b68ccdd6-nvrb2   1/1     Running   0          10m
nginx-web-5bf45d88df-xpbq9      1/1     Running   0          16h
ivo@kube-master:~/kubedirector$ kubectl get KubeDirectorApp
No resources found in default namespace.

**Comment by joel-bluedata** [comment]
So, this kind of error:
```
Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-cassandra-3.11.json": Internal error occurred: failed calling webhook "validate-cr.kubedirector .hpe.com": Post "https://kubedirector-validator.default.svc:443/validate?timeout=30s": context deadline exceeded
```
means that the validation webhook for CRs is not responding. There could be various reasons for webhook failure, but we can rule most of them out because the process got past the "Waiting for KubeDirector to start" phase which means that the KubeDirector pod itself is running and has successfully created the MutatingWebhookConfiguration resource.

It could be that your K8s cluster doesn't have support for webhooks enabled, or that there is some fundamental networking issue in the cluster. Hard to say given only the info we have so far.

Can you dump the KubeDirector pod logs to a txt file and attach them to this issue?

Also, what kind of K8s cluster are we dealing with here? How was it created?

**Comment by Ivaylo68Ma** [comment]
Hi Joel,
thanks for the comment.
The problem was with network pod calico - it was in  CrashLoopBackOff status. 
I have reinstalled everithing from the scratch and now it is working. :)

**Comment by joel-bluedata** [comment]
👍
