### ISSUE TITLE
Wiki documentation clarification required for defaultPersistDirs

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#410]
The docs for defaultPersistDirs state:

> The default list of filesystem directories to be placed on persistent shared storage for role members (if requested). These should be the app-required directories; KubeDirector itself may need to mount other directories as well. Optional. Pattern per element: ^/.*[^/]$

However, the ubuntu18.04 image has the following: `"defaultPersistDirs" : ["/home"]` but `/home` and `/etc` appear to be persisted.

> KubeDirector itself may need to mount other directories as well

How does KD decide which other directories to mount?

**Comment by kmathur2** [comment]
KD has a default set of dirs that are always persisted
Namely - ["/etc", "/opt", "/usr"], so defaultPersistDirs is on top of these dirs

**Comment by snowch** [comment]
Thanks, @kmathur2.  The Ubuntu image specifies `/home`, but only `/etc/` and `/home` were persisted - not `/opt` or `/usr`.

**Comment by kmathur2** [comment]
That is strange, I will verify and get back to you on this

**Comment by swamibluedata** [comment]
KubeDirector will persist /etc if you don't have an app config package in your app definition CR. It will persist /etc, /opt and /usr only if app config is persistent.

**Comment by snowch** [comment]
Thanks, @swamibluedata - would it be possible to add that statement to the wiki documentation for `defaultPersistDirs`?

**Comment by snowch** [comment]
Nevermind, I've documented it here https://hpe-container-platform-community.github.io/learn-kubedirector/docs/kd-img-dev/defaultpersistdirs#why-was-etc-persisted
