### ISSUE TITLE
Question: What are the KD lifecycle events?

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#414]
The changelog for 5.0 states:

> A KD app can define which lifecycle events (among "configure"/"addnodes"/"delnodes") the members in a role actually care about being notified for. If we can skip sending notifications to a member, then it matters less if that member is down when a KD cluster is reconfigured.

Where can I find a list of all lifecycle events and their description?

**Comment by swamibluedata** [comment]
configure, addnodes and delnodes

**Comment by snowch** [comment]
Thanks, @swamibluedata

**Comment by kmathur2** [comment]
We will be adding reconnect also shortly.
