### ISSUE TITLE
Systemd checks report issue in Ubuntu image

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#417]
The Ubuntu image systemd check returns an error, preventing KD appconfig packages from working. 

```console
root@kdss-mdz2r-0:/# systemctl status systemd-journald
System has not been booted with systemd as init system (PID 1)
```

For more info: https://github.com/bluek8s/kubedirector/issues/415

**Comment by kmathur2** [comment]
@joel-bluedata are you looking at this already? @Vellanci  and I were going to look at this also. Let us know.

**Comment by Vellanci** [comment]
According to my findings Systemd doesn't work in containers out of box. One way of fixing it is by adding cgroup mount and making it privileged. Another one way is by adding more tmpfs mounts (for /run, /run/lock) and allowing it to be unprivileged. For kubernetes it can implemented by using emptyDir and localPath mounts. Also Dockerfile should install systemd and couple of env vars. I managed to get it working with simple kubernetes pod. I will continue investigation on how to do it with KD.

**Comment by kmathur2** [comment]
Adding @swamibluedata for visibility

**Comment by Vellanci** [comment]
I noticed "systemdRequired" that implements the unprivileged way I mentioned before. Apart from mount points created by this feature, for Ubuntu Systemd /run/lock is also required to be mounted. Also current ubuntu image doesn't run systemd as PID 1 (entrypoint) process.

**Comment by Vellanci** [comment]
I managed to solve the issue with two changes:
1. On KD side generate /run/lock tmpfs volume mount (/run, /tmp is already generated at stateful set creation time).
2. On Ubuntu app side update image to run systemd as entrypoint process.
