### ISSUE TITLE
Does KD support using third party container images? 

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#429]
Can we use third party container images instead of the BlueData ones?

**Comment by joel-bluedata** [comment]
Absolutely. The only requirement is that the image be hosted at a repo that the K8s cluster can access.

Of course this leaves open the question of whether the image will do what you expect, when it is used in a kdcluster. If it requires special pod configuration that is not currently modeled by kdapp/kdcluster, then it may be a nonstarter for now (but we'd like to hear about the issue). If it requires some sort of action to be taken when the pod starts, that may be a thing that needs an app config script which KD can trigger.

If you've hit an issue using some image other than the example apps, let us know.

----------

I'm doing a scrub of the issues that were opened while I was on leave (and are still open). For issues like this one that require some followup, I'll leave it open for a couple of weeks and then close it if no further activity.
