### ISSUE TITLE
placement constraints

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#48]
Think about how we could/should expose affinity and nodeSelector configuration for the deployed pods.

**Comment by joel-bluedata** [comment]
Current thinking is that node selector, affinity, and labelling for pods are all things that could need to be enforced in the kdapp and/or requested in the kdcluster.

We currently have support for the "requested in the kdcluster" part of that story for labels. We should probably extend that to node selector and affinity, and also (for all those things) look into expressing them in the kdapp as well.

**Comment by Vellanci** [comment]
As discussed with @kmathur2 the implementation for now will be adding affinity field as part of RoleSpec specified in kdclusters and passing it to pods. Also a good idea is to add affinity to list of pods in kdclusters' status. The affinity is more advanced and therefore top priority for this feature. Node Selector and Node Name fields can be added later as well.
