### ISSUE TITLE
support KD admin configuration/settings

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#5]
We will need a way to persist KD-global administrative settings that can be edited by a correctly-privileged user. E.g. a ConfigMap for KD or another type of custom resource.

**Comment by riteshja** [comment]
Right now, in our `rbac-default.yaml`, we create a `ServiceAccount` with the name `kubedirector` who is bound to the kubedirector `ClusterRole`.

Is KD-Admin going to be a new `ServiceAccount` or kubedirector `ServiceAccount` itself is KD-Admin?

**Comment by joel-bluedata** [comment]
The service account named "kubedirector" has the credentials used by the KubeDirector deployment to interact with the k8s API (with some very wide privileges). A human (or other non-KubeDirector client) using the k8s API would not use those credentials.

Whatever method we design for applying administrative settings to KD, it will involve using the k8s API to create or modify some k8s object, whether that is a ConfigMap or some new custom resource type. RBACs can be used to restrict who is allowed to do that, based on the type of resource or even the specific name of the resource.
