### ISSUE TITLE
typo(?) in NVIDIA_VISIBLE_DEVICES environment var

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#507]
We're setting NVIDIA_VISIBLE_DEVICE (rather than NVIDIA_VISIBLE_DEVICES); cf. pkg/executor/types.go

**Comment by jear** [comment]
My understanding is the following : Kubedirector is working today with any string, nvidia.com/gpu , or A100 MIG canonical naming, for instance nvidia.com/mig-3g-20gb. A test would be to modify  NVIDIA_VISIBLE_DEVICE to NVIDIA_VISIBLE_DEVICES, and check if KD is still able to handle A100 MIG devices. I will upgrade to 0.6.2 to test nodeSelector which is usually used with MIG. I think that managing GPU and MIG tenant quota can be tricky due to a CUDA limitation (P2P = Peer-to-peer) that prevents a pod to have 2 MIGS of the same board and be able to launch 2 independant workload, as we are used to do with 2 usual GPU.

**Comment by joel-bluedata** [comment]
Currently KD will set that environment var to VOID if there are no resources of type "nvidia.com/gpu".

This is not having any effect because of the current typo, but if we fix the typo, then suddenly you'll be seeing NVIDIA_VISIBLE_DEVICES set to VOID even if the resource type is for example "nvidia.com/mig-3g-20gb". Would that be problematic?

We could change the behavior to for example instead check for any resource types with the prefix "nvidia.com/" but I want to make sure that would be correct behavior.

Also someone in email mentioned the CUDA_VISIBLE_DEVICES variable and I want to understand when/if that should be explicitly set by KD as well.

**Comment by jear** [comment]
I think it can work. Regarding CUDA_VISIBLE_DEVICES, my understanding is that this is used by TEnsorflow, unkess I miss something.

**Comment by jear** [comment]
My understanding for MIG quota and nvidia GPU operator in imported cluster, containing both MIG-capable and non-MIG-capable GPU…

As soon as you enable MIG, for all GPU type, we should not rely anymore only  on nvidia.com/gpu string in requests/limits.

We should  add  other labels that the operator has added on the node.


# Identify the node with the A100 by playing with jq
kubectl get node -o json | jq '.items[].metadata.labels' | grep machine
  "nvidia.com/gpu.machine": "ProLiant-BL460c-Gen8",
  "nvidia.com/gpu.machine": "ProLiant-DL380-Gen10",
  "nvidia.com/gpu.machine": "ProLiant-DL380-Gen10",

# there might hosts without GPU !
kubectl get node -o json | jq '.items[].metadata.labels' | grep hostname
  "kubernetes.io/hostname": "worker-gpu-1",
  "kubernetes.io/hostname": "worker-gpu-2",
  "kubernetes.io/hostname": "worker-gpu-3",
  "kubernetes.io/hostname": "worker-gpu-7",


kubectl get node -o json | jq '.items[].metadata.labels' | grep product
  "nvidia.com/gpu.product": "Tesla-M6",
  "nvidia.com/gpu.product": "Tesla-T4",
  "nvidia.com/gpu.product": "NVIDIA-A100-PCIE-40GB",

kubectl get node -o json | jq '.items[].metadata.labels' | grep -i family
  "nvidia.com/gpu.family": "maxwell",
  "nvidia.com/gpu.family": "turing",
  "nvidia.com/gpu.family": "ampere",


kubectl get node -o json | jq '.items[].metadata.labels' | grep count
  "nvidia.com/gpu.count": "1",
  "nvidia.com/gpu.count": "3",
  "nvidia.com/gpu.count": "1",
  "nvidia.com/mig-1g.5gb.count": "2",
  "nvidia.com/mig-2g.10gb.count": "1",
  "nvidia.com/mig-3g.20gb.count": "1",

kubectl get node -o json | jq '.items[].metadata.labels' | grep -i slices.ci
  "nvidia.com/mig-1g.5gb.slices.ci": "1",
  "nvidia.com/mig-2g.10gb.slices.ci": "2",
  "nvidia.com/mig-3g.20gb.slices.ci": "3",

kubectl get node -o json | jq '.items[].metadata.labels' | grep -i slices.gi
  "nvidia.com/mig-1g.5gb.slices.gi": "1",
  "nvidia.com/mig-2g.10gb.slices.gi": "2",
  "nvidia.com/mig-3g.20gb.slices.gi": "3",

# The strange thing... mixed for non-MIG GPU like T4 or M6 ?????
kubectl get node -o json | jq '.items[].metadata.labels' | grep -i strategy
  "nvidia.com/mig.strategy": "mixed",
  "nvidia.com/mig.strategy": "mixed",
  "nvidia.com/mig.strategy": "mixed",

**Comment by joel-bluedata** [comment]
Need to revisit this.

**Comment by jear** [comment]
by the way... I have worked with nvidia and rancher for a customer who needs  GPU operator for SLES15-SP3. nvidia will release cuda images. But my tests are working fine so far. No reboot needed. Just use helm upgrade and kubectl apply to change MIG strategy and geometry. My notes are here https://github.com/jear/nvidia-gpu-operator-sles15-sp3-driver

**Comment by joel-bluedata** [comment]
OK so here's my bottom-line understanding so far. Along with fixing the typo, we need some other changes:

If there is any resource request prefixed with "nvidia.com/" that is set to some nonzero value, then we should NOT set NVIDIA_VISIBLE_DEVICES. This is different from our current behavior which only specifically checks for "nvidia.com/gpu".

Otherwise, we should set NVIDIA_VISIBLE_DEVICES. From the [NVidia docs](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html) it looks like we should be setting it to "void" though, rather than "VOID", although perhaps case doesn't matter.

For reference the original issue this was supposed to fix was #263 so we need to check it actually fixes it!

Other things to reference are the PR that originally made this change (#302) and a google doc that looks at the env var behavior in detail ( https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit ).

I belieeeeeve that if we are setting NVIDIA_VISIBLE_DEVICES to void that we will *not* need to set CUDA_VISIBLE_DEVICES, as it looks like something that is "on top of" the devices exposed by NVIDIA_VISIBLE_DEVICES. But please verify that.

**Comment by joel-bluedata** [comment]
@CybervisionVolodymyrPogorelov note we have an existing PR which basically does this, with the exception of fixing the value from "VOID" to "void": PR #517 

Really just need testing now.
