### ISSUE TITLE
improved implementation of "systemd support"

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#6]
Currently if an app type declares the need for systemd support, we always add the various volume and mount specs per executor.generateSystemdSupport.

This is unnecessary on RHEL/CentOS hosts, and even disallowed on some (e.g. OpenShift so add this to issue #1).

We should use generateSystemdSupport only if necessary. It would be nice if we could discover the "if necessary" part, but otherwise we could at least implement it as a global setting per issue #5.

**Comment by joel-bluedata** [comment]
The workaround for this on OpenShift is to set systemdRequired to false in the KubeDirectorApp CRs (e.g. those in the example_catalog directory) before creating those CRs.

**Comment by joel-bluedata** [comment]
We're going to do the global config setting. If this global flag is set, then we can skip systemd-support setup for a cluster even if the app CR says that systemd support is required.

**Comment by swamibluedata** [comment]
So far we have been avoiding fetching/using config CR outside of webhook. For this feature we do need to cache this in cluster cr?

**Comment by joel-bluedata** [comment]
Hmm good point.

So as we've talked about before... the right answer both for this CR and for the app CRs is to watch them and cache them. Is that too big of a change for 0.2?

I don't think that caching in the cluster CR (during one handler run) is helpful for the config CR, because we're only going to look at it once in any given handler run.
