### ISSUE TITLE
differentiate nonspecified setup_package from emptystring

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#85]
The app CR author should be allowed to specify emptystring for a role's setup package in order to indicate that the role has no setup package, even when there is a top-level default package.

Currently though we can't differentiate emptystring from unspecified, in the field of the deserialized NodeRole structure. So we should change that field type from string to string-pointer and make the distinction.

For consistency we *could* change the top-level setup_package field, in AppSpec, to string-pointer type as well. The question really is in how we choose to treat the case where neither the AppSpec nor the NodeRole have setup_package specified. Do we consider that to be a mistake and flag it as an error? Or do we treat it as "no setup package", i.e. the same way as if one or both of those fields had been emptystring? if the latter, then we can leave the AppSpec field as string type.

**Comment by joel-bluedata** [comment]
We also need to allow emptystring in the schema pattern, and document its behavior on the wiki.

(Unless there's a better way to indicate "no setup package"?)

**Comment by joel-bluedata** [comment]
(@swamibluedata  reminded me that the setup_package value is actually an object rather than just the import_url string.)

At this point I'm thinking that we need to always make the "no setup package" case explicit, for clarity. I.e. at the top level you must always specify some value for setup_package, and at the role level you can omit setup_package to indicate "no override".

Some possible ways we could model the explicit "no setup package" case using the existing object:
* Have an alternate value for the setup_package property. For example allow it to be set to false rather than to the usual object value. However the current k8s validation schema isn't full-featured enough to support something like that (and it's a little odd). We could give up on schema validation here and just handle it dynamically...
* Or, have some other flag inside the object that explicitly indicates whether we are using a setup package or not. If true, you must specify both import_url and config_api_version. If false, specify neither. That's a little baroque.

As for the other approach...

We've been talking about dropping config_api_version since we don't need it yet. This is related to the question of how much we want the config API and app metadata stuff to track the implementation used for EPIC catalog entries... will we try to keep those more or less in sync as some global thing used across multiple products/projects? That would be nice in some ways but maybe too ambitious. We have a meeting scheduled to talk about some relevant topics so we might get more clarity on that soon. @kcsraju may want to chime in here.

Anyway, this is alpha code so we could drop the config_api_version complication now and bring it back later if we need it. I would be completely OK with that unless it is blindingly obvious that we will need it. IF we do that, then the approach should be:
- setup_package just takes a string value, which is the package location. Maybe we rename the property to setup_package_url.
- At the top level, setup_package_url MUST be specified. Give it an emptystring value if there is no package.
- At the role level, setup_package_url will be implemented as a string pointer internally. It can have three kinds of values:
  - unspecified: the top-level value is in effect for this role
  - specified emptystring: this role has no setup package (overrides top level)
  - specified nonempty URL: the location of this role's setup package (overrides top level)

One thing I have some concern about is how/if kubectl distinguishes between "unset property" and "property set to emptystring" when displaying these objects. I will experiment there when I have the chance. Even if kubectl does show the emptystring-valued property it might still not be clear enough what is going on... that could push us toward finding a better representation of that case. (Similarly for the way we model the override of persist_dirs back to default.)

**Comment by kcsraju** [comment]
As you know, KD generates the config meta json - there is no indirection (like an agent). That means KD must be aware of the `config_api_version` so it can generate the right `" format"` of the metadata that BDVLCI library understands. The config_api_version (or some versioning schema) is also necessary in KD when invoking the app's configuration scripts - say a new cmdline arg to `startscript` is added at some later time.

**Comment by swamibluedata** [comment]
@kcsraju configmeta will still have config_api_version. But we can drop this from CR for now and just hard code in KD. This will help implement this particular feature.

**Comment by kcsraju** [comment]
Thanks, @swamibluedata that makes sense.

**Comment by kcsraju** [comment]
JSON explicitly allows `null` as a value. Did you guys already rule that out in favor of a string `"none"`?

**Comment by kcsraju** [comment]
I can't comment about the YAML representation but unmarshalling looks straightforward to me: https://play.golang.org/p/Wganpf4sbO. Maybe I am missing something.

**Comment by joel-bluedata** [comment]
The use of RawMessage is a nice idea yeah.

I guess I don't feel strongly about `null` vs "none", if `null` is actually usable. (I'll still want to re-check to see how the `get -o yaml` output represents `null` and if it is distiguishable from not-set.) On the one hand, "none" is a magical-string-value which is distasteful to use for a property that also takes other string values. On the other hand, "none" is very clear about its meaning.

`null` is probably clear enough though. If the YAML output looks OK then I'd be happy with using that.

**Comment by kcsraju** [comment]
Sounds good to me. By the way, I can't take credit for that example. I found it when I was reading up on JSON in go.

**Comment by joel-bluedata** [comment]
Hey @kcsraju would you want to take ownership of this one?

One other thing that has come up, related both to this issue and also #77, which is: how/if we want to support the case where the startscript is baked into the container image. Issue #77 as it currently stands is basically saying that if there is no setup package, we can't/shouldn't invoke the startscript. But maybe that's not quite right. Maybe our various setup_package properties here really need to be able to express three different things: "no package", "downloadable package at this URL", and "package already in the image".  ... ?
